// fetch-gifs.mjs — run once: node fetch-gifs.mjs
// Downloads exercise GIFs from ExerciseDB and saves them to public/gifs/

import fs from 'fs';
import path from 'path';
import https from 'https';

const API_KEY = '1d2aac029dmsh866da1c8feb709cp1e9db1jsn64d85165b480';
const OUT_DIR = path.resolve('./public/gifs');

if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

// exercise name → ExerciseDB search term
const EXERCISES = {
  'flat-bench-press':               'barbell bench press',
  'incline-dumbbell-press':         'incline dumbbell press',
  'chest-fly-cable-fly':            'cable fly',
  'cable-tricep-pushdown':          'cable triceps pushdown',
  'dumbbell-lateral-raises':        'dumbbell lateral raise',
  'push-ups':                       'push up',
  'lat-pulldown':                   'lat pulldown',
  'seated-cable-row':               'seated cable row',
  't-bar-row':                      't bar row',
  'face-pulls':                     'cable face pull',
  'barbell-bicep-curls':            'barbell curl',
  'hammer-curls':                   'dumbbell hammer curl',
  'incline-walk-cycling':           'walking',
  'plank':                          'plank',
  'mountain-climbers':              'mountain climber',
  'hanging-leg-raises':             'hanging leg raise',
  'overhead-press':                 'barbell overhead press',
  'shoulder-press-machine':         'machine shoulder press',
  'rear-delt-fly':                  'rear delt fly',
  'shrugs':                         'barbell shrug',
  'overhead-cable-tricep':          'cable overhead tricep extension',
  'romanian-deadlift':              'romanian deadlift',
  'wide-grip-lat-pulldown':         'lat pulldown wide',
  'chest-supported-row':            'incline dumbbell row',
  'ez-bar-curls':                   'ez barbell curl',
  'barbell-squat':                  'barbell squat',
  'walking-lunges':                 'dumbbell walking lunge',
  'leg-extensions':                 'leg extension',
  'leg-curls':                      'leg curl',
  'standing-calf-raises':           'standing calf raise',
};

function fetchJSON(url, headers) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    });
    req.on('error', reject);
  });
}

function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    // Handle redirects
    const follow = (u) => {
      https.get(u, res => {
        if (res.statusCode === 301 || res.statusCode === 302) {
          follow(res.headers.location);
          return;
        }
        const file = fs.createWriteStream(dest);
        res.pipe(file);
        file.on('finish', () => file.close(resolve));
        file.on('error', reject);
      }).on('error', reject);
    };
    follow(url);
  });
}

async function main() {
  const manifest = {};
  const entries = Object.entries(EXERCISES);

  for (const [slug, searchTerm] of entries) {
    const destPath = path.join(OUT_DIR, `${slug}.gif`);

    // Skip if already downloaded
    if (fs.existsSync(destPath)) {
      console.log(`[SKIP] ${slug} — already exists`);
      manifest[slug] = `/gifs/${slug}.gif`;
      continue;
    }

    const url = `https://exercisedb.p.rapidapi.com/exercises/name/${encodeURIComponent(searchTerm)}?limit=1&offset=0`;
    console.log(`[FETCH] ${slug}  →  "${searchTerm}"`);

    try {
      const data = await fetchJSON(url, {
        'x-rapidapi-key': API_KEY,
        'x-rapidapi-host': 'exercisedb.p.rapidapi.com',
      });

      const gifUrl = data?.[0]?.gifUrl;
      if (!gifUrl) {
        console.warn(`  ✗ No GIF found for "${searchTerm}"`);
        console.warn(`  Response: ${JSON.stringify(data).slice(0, 200)}`);
        continue;
      }

      console.log(`  ✓ Downloading: ${gifUrl}`);
      await downloadFile(gifUrl, destPath);
      manifest[slug] = `/gifs/${slug}.gif`;
      console.log(`  ✓ Saved → public/gifs/${slug}.gif`);

      // Be polite to the API — small delay between requests
      await new Promise(r => setTimeout(r, 400));
    } catch (err) {
      console.error(`  ✗ Error for ${slug}:`, err.message);
    }
  }

  // Write manifest so the app can import it statically
  const manifestPath = path.resolve('./src/utils/gifManifest.js');
  const js = `// Auto-generated by fetch-gifs.mjs — do not edit manually\nexport const GIF_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(manifestPath, js);
  console.log('\n✅  Manifest written to src/utils/gifManifest.js');
  console.log(`✅  ${Object.keys(manifest).length}/${entries.length} GIFs ready`);
}

main();
